services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    networks:
      - appnet
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - env/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge