"""Add bucket_started_at column to domain_check

Revision ID: 74e90f1228ab
Revises: 088aa4fed315
Create Date: 2026-05-19 18:13:00.716364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "74e90f1228ab"
down_revision: Union[str, Sequence[str], None] = "088aa4fed315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domain_check",
        sa.Column(
            "bucket_started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("domain_check_domain_id_idx"),
        table_name="domain_check",
    )
    op.create_index(
        op.f("domain_check_domain_id_idx"),
        "domain_check",
        [
            "domain_id",
            sa.literal_column("bucket_started_at DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("domain_check_domain_id_idx"),
        table_name="domain_check",
    )
    op.create_index(
        op.f("domain_check_domain_id_idx"),
        "domain_check",
        ["domain_id", sa.literal_column("checked_at DESC")],
        unique=False,
    )
    op.drop_column(
        "domain_check",
        "bucket_started_at",
    )
    # ### end Alembic commands ###
