class MonitoringConfig:
    ROUTER_PREFIX = "/domains"
    ROUTER_TAG = "domains"

    MAX_DOMAIN_TITLE_LENGTH = 64
    MAX_DOMAINS_PER_USER = 100

    DOMAIN_PAGE_SIZE_MIN = 1
    DOMAIN_PAGE_SIZE_DEFAULT = 10
    DOMAIN_PAGE_SIZE_MAX = 100

    CHECK_INTERVAL_SECONDS = 5 * 60  # 5 minutes

    CHECKER_MAX_RETRIES = 3
    CHECKER_RETRY_BASE_DELAY = 0.5
    CHECKER_RETRY_MAX_DELAY = 5.0
    CHECKER_CONNECT_TIMEOUT = 5.0
    CHECKER_READ_TIMEOUT = 10.0
    CLIENT_USER_AGENT_HEADER = "DomainMonitor/1.0 (+health-check)"

    WORKERS_POOL_PROBE_WORKERS_COUNT = 30
    WORKERS_POOL_WRITER_WORKERS_COUNT = 3
    WORKERS_POOL_PROBE_QUEUE_SIZE = 300
    WORKERS_POOL_WRITE_QUEUE_SIZE = 300

    SCHEDULER_ID = "domain_check_cycle"
    SCHEDULER_NAME = "Domain check cycle"
    SCHEDULER_MISFIRE_GRACE_SECONDS = 30
    SCHEDULER_MAX_INSTANCES = 1  # Skip tick if previous cycle has not finished yet.
    SCHEDULER_COALESCE = True  # Merge missed scheduler ticks into a single execution.

    RECENT_CHECKS_LIMIT_DEFAULT = 3  # Number of recent checks returned per domain.
    RECENT_CHECKS_LIMIT_MAX = 96
    RECENT_CHECKS_WINDOW_INTERVALS_MIN = 1
    RECENT_CHECKS_WINDOW_INTERVALS_DEFAULT = 1
    RECENT_CHECKS_WINDOW_INTERVALS_MAX = 24
