"""first migration

Revision ID: 7f9bbc11449f
Revises:
Create Date: 2026-05-10 12:36:54.762841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7f9bbc11449f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("domain_pkey")),
        sa.UniqueConstraint("name", name=op.f("domain_name_key")),
    )
    op.create_table(
        "domain_check",
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("unknown", "up", "degraded", "down", name="monitor_status"),
            nullable=False,
        ),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_text", sa.String(), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
            name=op.f("domain_check_domain_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("domain_check_pkey")),
    )
    op.create_index(
        op.f("domain_check_domain_id_idx"),
        "domain_check",
        ["domain_id", sa.literal_column("checked_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_domain",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
            name=op.f("user_domain_domain_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_domain_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_domain_pkey")),
        sa.UniqueConstraint(
            "user_id", "domain_id", name="user_domain_user_id_domain_id_key"
        ),
    )
    op.create_index(
        op.f("user_domain_domain_id_idx"), "user_domain", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("user_domain_user_id_idx"), "user_domain", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_domain_user_id_idx"), table_name="user_domain")
    op.drop_index(op.f("user_domain_domain_id_idx"), table_name="user_domain")
    op.drop_table("user_domain")
    op.drop_index(op.f("domain_check_domain_id_idx"), table_name="domain_check")
    op.drop_table("domain_check")
    op.drop_table("domain")

    op.execute("DROP TYPE IF EXISTS monitor_status")
    # ### end Alembic commands ###
